# Generated by Django 3.0.2 on 2021-04-14 14:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_create_dt', models.DateTimeField(auto_now_add=True)),
                ('message_heading', models.TextField()),
                ('message_body', models.TextField()),
                ('message_expires', models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 36, 15, 742855, tzinfo=utc))),
                ('message_n_likes', models.IntegerField(default=0, editable=False)),
                ('message_n_dislikes', models.IntegerField(default=0, editable=False)),
                ('message_n_comments', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ('-message_create_dt',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=8, verbose_name=['Tech', 'Politics', 'Health', 'Sport'])),
                ('message_id', models.ManyToManyField(blank=True, related_name='message_topics', to='piazza.Message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_topic',
            field=models.ManyToManyField(related_name='messages', to='piazza.Topic'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_create_dt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='piazza.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('comment_create_dt',),
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, max_length=7, verbose_name=['Like', 'Dislike'])),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='piazza.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message_id', 'user')},
            },
        ),
    ]
