# Generated by Django 3.0.2 on 2021-04-14 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 15, 36, 43, 186673, tzinfo=utc)),
        ),
    ]
