# Generated by Django 3.0.2 on 2021-04-14 15:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0002_auto_20210414_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 16, 46, 29, 545385, tzinfo=utc)),
        ),
    ]
