# Generated by Django 3.0.2 on 2021-04-15 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0003_auto_20210414_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_n_comments',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_n_dislikes',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_n_likes',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 22, 27, 40, 283986, tzinfo=utc)),
        ),
    ]
