# Generated by Django 3.0.2 on 2021-04-16 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0005_auto_20210416_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 21, 43, 47, 221530, tzinfo=utc)),
        ),
    ]
