# Generated by Django 3.0.2 on 2021-04-17 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0006_auto_20210416_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_create_dt',)},
        ),
        migrations.AlterField(
            model_name='message',
            name='message_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 10, 54, 57, 132215, tzinfo=utc)),
        ),
    ]
