# Generated by Django 3.0.2 on 2021-04-17 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0007_auto_20210417_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 11, 12, 55, 158202, tzinfo=utc)),
        ),
    ]
